### ISSUE TITLE
Não redireciona para o site

### ISSUE THREAD

**Issue by FabioZumbi12** [luizwbr/MoIP-VirtueMart-3#1]
Olá Luiz, estou aqui denovo te dando trabalho kkkk Mas só vc que fez os plugins para os pagamentos Brasileiros então estou usando todos.

Instalei e configurei todos dados na pagina e configuração mas ao final da compra o cliente não é redirecionado para o site do Moip, e o link do que aparece pra mim quando vou em pedido é este: http://areaz12server.net.br/0

E o carrinho também não é limpo: http://prntscr.com/c3k1ys

Obrigado e desculpe o incomodo.

**Comment by luizwbr** [comment]
Fabio, deu algum problema de jQuery neste site. O plugin do MoIP não redireciona para o site deles, é um plugin transparente, igual ao do PagSeguro.
Tenta instalar o jQuery Easy para remover duplicatas desta biblioteca: http://extensions.joomla.org/extension/jquery-easy
O carrinho não é limpo para que o cliente tenha a possibilidade de tentar novamente o pagamento. Ele só é limpo depois que a transação é confirmada ou cancelada.

**Comment by Victortubi** [comment]
Olá Luiz. Tive o mesmo problema do Fábio. Instalei a extensão que você indicou e continuo sem abrir o método de pagamento.

Esse é o site: www.prestomusica.com

Obrigado!

**Comment by luizwbr** [comment]
Victor, usa o mesmo plugin que o Fabio passou, vai funcionar.
